# Generated by Django 3.0.3 on 2020-05-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tckrSymb', models.CharField(max_length=20, unique=True, verbose_name='tckrSymb')),
                ('sgmtNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='sgmtNm')),
                ('mktNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='mktNm')),
                ('sctyCtgyNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='SctyCtgyNm')),
                ('isin', models.CharField(blank=True, max_length=20, null=True, verbose_name='isin')),
                ('cFICd', models.CharField(blank=True, max_length=20, null=True, verbose_name='cFICd')),
                ('crpnNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='crpnNm')),
                ('corpGovnLvlNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='corpGovnLvlNm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Moviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'COMPRA'), (1, 'VENDA')], null=True, verbose_name='type')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('total_costs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costs')),
                ('date', models.DateField(verbose_name='date')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Instrument')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
