# Generated by Django 3.0.3 on 2020-05-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
        ('wallet', '0003_auto_20200504_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviment',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.Instrument'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
