# Generated by Django 3.0.3 on 2020-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20200507_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
