# Generated by Django 3.0.3 on 2020-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20200717_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviment',
            name='type',
        ),
        migrations.AddField(
            model_name='moviment',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'COMPRA'), (1, 'VENDA')], null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='position',
            name='total_selic',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='total value'),
            preserve_default=False,
        ),
    ]
