# Generated by Django 3.0.3 on 2020-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20200718_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='total_quantity',
            field=models.IntegerField(null=True, verbose_name='total quantity'),
        ),
    ]
