# Generated by Django 3.0.3 on 2020-07-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20200722_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='net_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='net value'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_selic',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total value'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total value'),
        ),
        migrations.AlterField(
            model_name='position',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='transaction value'),
        ),
    ]
