# Generated by Django 3.0.3 on 2020-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20200722_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_selic',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total selic'),
        ),
    ]
