# Generated by Django 3.0.3 on 2020-07-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20200724_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='quantity'),
        ),
    ]
