# Generated by Django 3.0.3 on 2020-07-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20200730_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total quantity'),
        ),
    ]
