# Generated by Django 3.0.3 on 2020-07-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_auto_20200730_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_selic',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total selic'),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='quantity'),
        ),
    ]
