# Generated by Django 3.0.3 on 2020-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_auto_20200731_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_selic',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='position selic'),
        ),
    ]
