# Generated by Django 3.0.3 on 2020-09-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_position_current_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='current_value',
            new_name='total_networth',
        ),
    ]
