# Generated by Django 3.0.3 on 2020-09-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_auto_20200905_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='total_dividends',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total dividends'),
        ),
    ]
