# Generated by Django 3.0.3 on 2020-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_position_total_dividends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_dividends',
            field=models.DecimalField(decimal_places=9, max_digits=20, null=True, verbose_name='total dividends'),
        ),
    ]
