# Generated by Django 3.0.3 on 2020-09-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0022_auto_20200811_1021'),
        ('wallet', '0023_auto_20200906_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='quantity')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='net value')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total value')),
                ('total_selic', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total selic')),
                ('total_dividends', models.DecimalField(decimal_places=9, max_digits=20, null=True, verbose_name='total dividends')),
                ('position_selic', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='position selic')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_provent', to='instrument.Instrument')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_provent', to='wallet.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
