# Generated by Django 3.0.3 on 2020-09-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_provent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provent',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='provent',
            name='document_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='provent',
            name='ex_date',
            field=models.DateField(default=None, verbose_name='ex date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provent',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='value per share'),
        ),
    ]
