# Generated by Django 3.0.3 on 2020-09-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_auto_20200907_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provent',
            name='ex_date',
            field=models.DateField(null=True, verbose_name='ex date'),
        ),
    ]
