# Generated by Django 3.0.3 on 2020-09-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_auto_20200907_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provent',
            name='payment_date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
    ]
