# Generated by Django 3.0.3 on 2020-09-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_auto_20200907_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provent',
        ),
    ]
