# Generated by Django 3.0.3 on 2020-09-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0022_auto_20200811_1021'),
        ('wallet', '0028_delete_provent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='quantity')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total value')),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend', to='instrument.Dividend')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'Provent',
                'verbose_name_plural': 'Provents',
            },
        ),
    ]
