# Generated by Django 3.0.3 on 2020-09-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0023_auto_20200907_1022'),
        ('wallet', '0029_walletprovent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletProvent',
            new_name='WalletStockProvent',
        ),
        migrations.CreateModel(
            name='WalletFIIProvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='quantity')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='total value')),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provento fii+', to='instrument.ProventoFII')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet fii+', to='wallet.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
