# Generated by Django 2.1.7 on 2019-04-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aporte',
            name='final_date',
            field=models.DateField(blank=True, null=True, verbose_name='Final Date'),
        ),
        migrations.AddField(
            model_name='aporte',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aporte.Grupo'),
        ),
    ]
