# Generated by Django 2.2 on 2019-07-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0006_auto_20190703_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selic',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
