# Generated by Django 2.1.7 on 2020-01-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('daily_factor', models.DecimalField(decimal_places=10, max_digits=11, verbose_name='Daily Fator')),
            ],
        ),
    ]
