# Generated by Django 3.0.3 on 2020-05-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tckrSymb', models.CharField(max_length=20, unique=True, verbose_name='tckrSymb')),
                ('sgmtNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='sgmtNm')),
                ('mktNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='mktNm')),
                ('sctyCtgyNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='SctyCtgyNm')),
                ('isin', models.CharField(blank=True, max_length=20, null=True, verbose_name='isin')),
                ('cFICd', models.CharField(blank=True, max_length=20, null=True, verbose_name='cFICd')),
                ('crpnNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='crpnNm')),
                ('corpGovnLvlNm', models.CharField(blank=True, max_length=20, null=True, verbose_name='corpGovnLvlNm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['-id'],
            },
        ),
    ]
