# Generated by Django 3.0.3 on 2020-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last update'),
        ),
    ]
