# Generated by Django 3.0.3 on 2020-05-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_instrument_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('eventDate', models.DateTimeField(verbose_name='event date')),
                ('dividends', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='dividends')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.Instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
