# Generated by Django 3.0.3 on 2020-05-13 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0003_auto_20200513_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 13, 23, 3, 39, 676306, tzinfo=utc), verbose_name='event date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_event', to='instrument.Instrument'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('instrument', 'event_date')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventDate',
        ),
    ]
