# Generated by Django 3.0.3 on 2020-05-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0005_event_stock_splits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='instrument.Instrument'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('open', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='open')),
                ('high', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='high')),
                ('low', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='low')),
                ('close', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='close')),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='adj_close')),
                ('volume', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='volume')),
                ('lastUpdate', models.DateTimeField(blank=True, null=True, verbose_name='last update')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='instrument.Instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
