# Generated by Django 3.0.3 on 2020-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0007_auto_20200515_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date'], 'verbose_name': 'PriceHistory', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('instrument', 'date')},
        ),
    ]
