# Generated by Django 3.0.3 on 2020-05-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0008_auto_20200515_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['tckrSymb'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
    ]
