# Generated by Django 3.0.3 on 2020-07-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0012_company_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='display',
        ),
    ]
