# Generated by Django 3.0.3 on 2020-07-11 01:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrument', '0015_auto_20200704_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='codigoCvm',
            field=models.IntegerField(blank=True, null=True, verbose_name='codigoCvm'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='external id'),
        ),
        migrations.AlterField(
            model_name='company',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('instrument', 'data')},
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ex_date', models.DateField(verbose_name='ex-date')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('accounting_date', models.DateField(blank=True, null=True, verbose_name='accounting date')),
                ('category', models.CharField(max_length=20, verbose_name='category')),
                ('document_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('factor', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='factor')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='instrument.Instrument')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
                'ordering': ['-ex_date'],
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ex_date', models.DateField(verbose_name='ex-date')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('accounting_date', models.DateField(blank=True, null=True, verbose_name='accounting date')),
                ('category', models.CharField(max_length=20, verbose_name='category')),
                ('document_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('value', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='value')),
                ('adjusted_value', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='adjusted value')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='instrument.Instrument')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
                'ordering': ['-ex_date'],
                'unique_together': {('instrument', 'ex_date', 'category', 'event_date', 'value')},
            },
        ),
    ]
