# Generated by Django 3.0.3 on 2020-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0016_auto_20200711_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='fraction_date',
            field=models.DateField(blank=True, null=True, verbose_name='fraction date'),
        ),
        migrations.AddField(
            model_name='split',
            name='fraction_price',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True, verbose_name='fraction price'),
        ),
        migrations.AddField(
            model_name='split',
            name='income_tax_price',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True, verbose_name='income tax price'),
        ),
        migrations.AlterField(
            model_name='split',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True, verbose_name='factor'),
        ),
    ]
