# Generated by Django 3.0.3 on 2020-08-11 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrument', '0020_auto_20200711_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProventoFII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ex_date', models.DateField(verbose_name='ex-date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('reference_date', models.DateField(blank=True, null=True, verbose_name='reference date')),
                ('value', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='value')),
                ('adjusted_value', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='adjusted value')),
                ('category', models.CharField(max_length=20, verbose_name='category')),
                ('details', models.CharField(blank=True, max_length=200, null=True, verbose_name='details')),
                ('factor', models.DecimalField(decimal_places=9, max_digits=20, null=True, verbose_name='value')),
                ('document_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proventosFII', to='instrument.Instrument')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
