# Generated by Django 3.0.3 on 2020-08-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0021_proventofii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proventofii',
            name='adjusted_value',
            field=models.DecimalField(decimal_places=9, max_digits=20, null=True, verbose_name='adjusted value'),
        ),
        migrations.AlterField(
            model_name='proventofii',
            name='value',
            field=models.DecimalField(decimal_places=9, max_digits=20, null=True, verbose_name='value'),
        ),
    ]
