# Generated by Django 3.0.3 on 2020-09-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0023_auto_20200907_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proventofii',
            options={'ordering': ['-ex_date'], 'verbose_name': 'Dividend FII', 'verbose_name_plural': 'Dividends FII'},
        ),
        migrations.AlterUniqueTogether(
            name='proventofii',
            unique_together={('instrument', 'ex_date', 'category', 'payment_date', 'value')},
        ),
    ]
