# Generated by Django 2.1.7 on 2019-04-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0002_auto_20190416_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aporte.Grupo'),
        ),
    ]
