# Generated by Django 2.1.7 on 2019-04-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0003_auto_20190416_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
