# Generated by Django 2.2 on 2019-07-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0005_selic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selic',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
    ]
