# Generated by Django 2.1.7 on 2020-01-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0008_auto_20190812_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selic',
        ),
    ]
