# Generated by Django 3.0.3 on 2020-04-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0011_auto_20200429_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='crpNm',
            new_name='crpnNm',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='mctyCtgyNm',
        ),
        migrations.AddField(
            model_name='instrument',
            name='sctyCtgyNm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SctyCtgyNm'),
        ),
    ]
