# Generated by Django 3.0.3 on 2020-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0012_auto_20200430_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'COMPRA'), (1, 'VENDA')], null=True, verbose_name='type'),
        ),
    ]
