# Generated by Django 3.0.3 on 2020-04-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('aporte', '0013_auto_20200430_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviment',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MovimentWallet',
        ),
    ]
