# Generated by Django 3.0.3 on 2020-04-30 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0014_auto_20200430_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 30, 8, 16, 41, 814942), verbose_name='date'),
            preserve_default=False,
        ),
    ]
