# Generated by Django 3.0.3 on 2020-04-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0015_moviment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviment',
            old_name='costs',
            new_name='total_costs',
        ),
        migrations.RenameField(
            model_name='moviment',
            old_name='price',
            new_name='total_investment',
        ),
    ]
