# Generated by Django 3.0.3 on 2020-05-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aporte', '0016_auto_20200430_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviment',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='moviment',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Moviment',
        ),
    ]
