# Generated by Django 3.0.3 on 2020-07-10 04:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrument', '0015_auto_20200704_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('instrument', 'data')},
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ex_dividend_date', models.DateField(verbose_name='ex-dividend date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('accounting_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('value', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='value')),
                ('adjusted_value', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='adjusted value')),
                ('dividends_type', models.CharField(max_length=10, verbose_name='dividends type')),
                ('document_link', models.URLField(blank=True, max_length=250, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='instrument.Instrument')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
                'ordering': ['-ex_dividend_date'],
                'unique_together': {('instrument', 'ex_dividend_date')},
            },
        ),
    ]
