# Generated by Django 3.0.3 on 2020-07-10 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrument', '0016_auto_20200710_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event2',
            new_name='Split',
        ),
        migrations.AlterModelOptions(
            name='split',
            options={'ordering': ['-ex_date'], 'verbose_name': 'Split', 'verbose_name_plural': 'Splits'},
        ),
    ]
