# Generated by Django 3.0.3 on 2020-07-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0018_auto_20200710_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacao',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events2', to='instrument.Instrument'),
        ),
    ]
