# Generated by Django 3.0.3 on 2020-07-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0018_instrument_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='codigoCvm',
            field=models.IntegerField(blank=True, null=True, verbose_name='codigoCvm'),
        ),
        migrations.AlterField(
            model_name='eventoacao',
            name='document_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
