# Generated by Django 3.0.3 on 2020-07-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0019_auto_20200710_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dividend',
            unique_together=set(),
        ),
    ]
