# Generated by Django 3.0.3 on 2020-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0019_auto_20200711_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacao',
            name='document_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
