# Generated by Django 3.0.3 on 2020-07-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0020_auto_20200710_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event2',
            options={'ordering': ['-ex_date'], 'verbose_name': 'Event2', 'verbose_name_plural': 'Events2'},
        ),
    ]
